### ISSUE TITLE
Incorporate additional ontologies into DICOM SNOMED to NCIt mapping

### ISSUE THREAD

**Issue by balhoff** [cancerDHC/tools#19]
In #7 @gaurav implemented incorporating of additional ontologies into the mapping tool. This ticket covers adding two additional ontologies:

- [x] [RadLex](http://radlex.org/) (see https://github.com/cancerDHC/operations/issues/48#issuecomment-694868279)
- [ ] <s>[AGROVOC](http://aims.fao.org/vest-registry/vocabularies/agrovoc)</s>

**Comment by decorons** [comment]
Why Agrovoc?  Doesn't seem needed for Cancer related things?

**Comment by decorons** [comment]
Also, FYI, RadLex is also in NCI Meta, so has been 'mapped' to other UMLS terminologies

**Comment by balhoff** [comment]
> Why Agrovoc? Doesn't seem needed for Cancer related things?

@gaurav what was that for? I just copied those tasks over from the previous issue.

**Comment by gaurav** [comment]
I've been looking through my notes, and I'm not sure why I added AGROVOC to this list -- I suspect I heard about it in the context of [SKOSMOS](http://skosmos.org/), and accidentally put it into this issue rather than one related to vocabulary visualization. I'll take it off the list here.

Since we've already included RadLex (via the BioPortal search API, see #21), I'll close this issue.

**Comment by decorons** [comment]
Thanks.  Probably Harold wanted it as a test because he knows it well.  Sherri
