### ISSUE TITLE
create example CRDC-H data in JSON/linkml

### ISSUE THREAD

**Issue by balhoff** [cancerDHC/tools#27]
For testing and demonstrating validation services, we need a collection of sample data adhering to the CRDC-H model.

- [x] Identify source data to be converted (possibly by hand at first); possibly some data from GDC and/or other nodes.
  - [x] [Ian Fore's example query](https://github.com/ianfore/cdatest/blob/8002ae1624b34e0e2f291022c295d4b778989de9/09CO022%20Example.ipynb) (GDC/PDC/IDC)
  - [ ] One complete project from GDC/PDC (*any suggestions?*)
  - [ ] *Add other ideas here*
- [x] Create repository (or just a folder) containing JSON examples.
  - [x] Also include TSV examples (GDC API allows us to download the data as TSV)

**Comment by gaurav** [comment]
How about https://github.com/cancerDHC/example-data as a repository name?

**Comment by gaurav** [comment]
This repository now exists: https://github.com/cancerDHC/example-data. I've also added two suggestions for possible data we could pull into the examples for now, but hopefully other CCDH people will have better ideas.

**Comment by gaurav** [comment]
CDA described their ETL process at our meeting yesterday. They import data from GDC/PDC via their APIs in JSON format, and then transforms it into the CDA representation (which is based on the CRDC-H model). They are working to create a mapping YAML file that would be used to handle this transformation process, both in terms of restructuring the data as well as mapping values to concepts. We can benefit from this transformation by using data from the CDA rather than directly from the GDC/PDC portals. If we develop our own methods for extracting data from other nodes, we should make sure those transformations are included in those mapping files eventually.

(Incidentally, during my conversation with @jiaola today, he pointed out that the code he's written at https://github.com/HOT-Ecosystem/crdc-node-models could potentially be used to generate a mapping YAML file from the CRDC-H model description in Google Sheets directly, which might potentially be useful to the CDA going forward.)

**Comment by balhoff** [comment]
See https://github.com/cancerDHC/example-data.
