### ISSUE TITLE
specify formats for data adhering to CRDC-H model

### ISSUE THREAD

**Issue by balhoff** [cancerDHC/tools#28]
This issue can be closed after creating some documentation on how to create structured formats which can be validated with CRDC-H.

- JSON (definitely)
- TSV - would be nice to define a standard way to use TSV with CRDC-H
- PFB - can there be a defined way to use PFB with CRDC-H

Examples should go in the repository created for #27.

This issue is covered by two issues:
- https://github.com/cancerDHC/example-data/issues/10
- https://github.com/cancerDHC/ccdhmodel/issues/59

**Comment by balhoff** [comment]
See also #15. It may turn out these issues are the same, but for now this one is specifically about CRDC-H and linkml.

**Comment by gaurav** [comment]
GDC supports exporting query results as [XML](https://github.com/cancerDHC/example-data/blob/c79c225e7ee577fe60619381d5a5da145d3cc4c7/cptac2-subject-09CO022/gdc_subject_09CO022.xml) and [TSV](https://github.com/cancerDHC/example-data/blob/c79c225e7ee577fe60619381d5a5da145d3cc4c7/cptac2-subject-09CO022/gdc_subject_09CO022.tsv). I think the [JSON representation](https://github.com/cancerDHC/example-data/blob/c79c225e7ee577fe60619381d5a5da145d3cc4c7/cptac2-subject-09CO022/gdc_subject_09CO022.json) is easier to read, but it's useful to know that these options exist.

PDC does not appear to support this, but it does allow lists of results to be exported as TSV/CSV on their website, so there's probably an API endpoint I haven't found yet to do this.

**Comment by balhoff** [comment]
A JSON format is produced in https://github.com/cancerDHC/example-data. We have some more work to do formalizing the format possibilities in Phase 3.

**Comment by gaurav** [comment]
There is a [LinkML-CSV](https://github.com/linkml/linkml-csv) package in development for converting instance data from a LinkML model in and out of CSV format, which might be really useful here.

**Comment by gaurav** [comment]
For our immediate needs, the LinkML instance format (in YAML) seems to be a good representation, and has been developed into [some exemplars](https://github.com/cancerDHC/data-model-harmonization/tree/79849628bca909ef113a6031bf1eb25498c48ee2/data-examples/f2f-2021-09-data-examples) by the CCDH Data Model Harmonization team as part of the CCDH Pilot. Future formats will probably be supported by adding generators to LinkML, so that data from any LinkML model can be converted into that format (e.g. see [the issue tracking an Avro/PFB generator for LinkML](https://github.com/linkml/linkml/issues/354)). Given that, I think we can close this issue until specific use-cases emerge from CDA and the CRDC nodes.
