### ISSUE TITLE
Label tasks that generate publicly visible deliverables

### ISSUE THREAD

**Issue by seandavi** [cancerDHC/tools#33]
Doing so might help to clarify to external viewers what work they should be looking for and when. I'm thinking about datasets, end-user code, apps, and APIs meant for public consumption. Contrast this with work that is more for internal purposes.

**Comment by gaurav** [comment]
Hi @seandavi! So sorry we overlooked this issue -- my notification settings weren't correct for this repository, so I missed this completely. I've created a "[product](https://github.com/cancerDHC/tools/labels/product)" label for tasks that should result in a publicly available product, rather than just being a bug fix or internal task. Thanks for the suggestion!
